### PR TITLE
Added level 12c with orbital brick

### PR DESCRIPTION
**Pull request by robinmdh**
which you have to match in speed
also added initial angualr velocity

~~somehow my end condition is borked though :(~~ (fixed)

Signed-off-by: Robin den Hertog <r.denhertog@ultimaker.com>

### CODE REVIEW

**Comment by daid** [comment]
Omg, this one is evil.

**Comment by daid** [comment]
Ps, next time would be nice to include a screenshot, like Ruben did with his pull requests ;-)

**Comment by robinmdh** [comment]
ok, will do. Strangely this was my first time making a cross fork PR.
Ruben's 2 huge orbiting boulders level is arguably more evil though.

**Comment by Ghostkeeper** [comment]
The brick gets stuck in its second orbit :cry:

**Comment by robinmdh** [comment]
@Ghostkeeper this is somewhat intentional, you just have to make it the first time.

**Comment by daid** [comment]
Like I said, it's evil.

**Pull request merged**
